version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony
    ports:
      - 8000:80
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony
    networks:
      - default

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

networks:
  default: