FROM php:fpm-stretch
RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y \
    git \
    tree \
    man \
    vim \
    ps \
    htop
RUN docker-php-ext-install \
    mysqli \
    pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN git clone https://github.com/AndreescuC/OhMyZshConfig.git /var/www/OhMyZshConfig
RUN sed -i 's/sudo//' /var/www/OhMyZshConfig/setup_config.sh && sed -i 's/sudo//' /var/www/OhMyZshConfig/setup_config.sh
RUN printf 'Y\n' apt-get install zsh
RUN printf '\nno\n' | /var/www/OhMyZshConfig/setup_config.sh

COPY /symfony /var/www/symfony

WORKDIR /var/www/symfony