FROM php:fpm-stretch
RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y git
RUN docker-php-ext-install \
    intl \
    mysqli \
    pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


COPY /symfony /var/www/symfony

WORKDIR /var/www/symfony