version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - 8000:80
    networks:
      - default

networks:
  default: